name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Build application
        run: docker build -t movements-service .

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install docker-compose
        run: curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose

      - name: Add docker-compose permission
        run: chmod +x /usr/local/bin/docker-compose

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Executing test
        run: docker-compose run --rm test

      - name: Stop services
        run: docker-compose down -v

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-report-movements-service
          path: ./reports

  docker-push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build application
        run: docker build -t mssalazarb/movements-service:latest .

      - name: Login to Docker Hub
        uses: actions/checkout@v2
        id: docker-hub
        env:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
        run: |
          docker login -u $username -p $password 

      - name: Docker push
        run: docker push mssalazarb/movements-service:latest
