name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Build application
        run: docker build -t movements-service .

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install docker-compose
        run: curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose

      - name: Add docker-compose permission
        run: chmod +x /usr/local/bin/docker-compose

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Executing test
        run: docker-compose run --rm test

      - name: Stop services
        run: docker-compose down -v

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-report-movements-service
          path: ./reports

  docker-push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker
        run: docker build -t movements-service:latest .

      - name: Docker Login
        shell: bash
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: echo "$USERNAME" && echo "$env:USERNAME"

      - name: Docker Login
        shell: bash
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: docker login -u "$USERNAME" -p "$TOKEN"

      - name: Docker Tag
        run: docker tag movements-service:latest mssalazarb/movements-service:latest

      - name: Docker push
        run: docker push mssalazarb/movements-service:latest
